package co.com.booker.stepdefinitions;

import co.com.booker.tasks.GetHealthCheck;
import io.cucumber.java.en.Then;

import static net.serenitybdd.screenplay.GivenWhenThen.seeThat;
import static net.serenitybdd.screenplay.actors.OnStage.theActorInTheSpotlight;
import static org.hamcrest.CoreMatchers.equalTo;

public class HealthCheckStepDefinition {

    @Then("should see the message {string} generated by the ping")
    public void shouldSeeThatTheServiceIsStillRunningSuccessfully(String message) {
        theActorInTheSpotlight().attemptsTo(
                GetHealthCheck.fromService(message));

        theActorInTheSpotlight().should(seeThat(
                actorSee -> GetHealthCheck.messageResponse(), equalTo(message)));
    }
}