[docker]
configs = [
        "selenium/standalone-chrome", "{\"browserName\": \"chrome\", \"platformName\": \"linux\", \"browserVersion\": \"100\"}",
        "selenium/standalone-edge", "{\"browserName\": \"MicrosoftEdge\", \"platformName\": \"linux\", \"browserVersion\": \"101\"}",
        "selenium/standalone-firefox", "{\"browserName\": \"firefox\", \"platformName\": \"linux\", \"browserVersion\": \"91\"}",
        "selenium/standalone-opera", "{\"browserName\": \"opera\", \"platformName\": \"linux\"}"
        ]
url = "http://127.0.0.1:2375"
video-image = "selenium/video:ffmpeg-4.3.1-20220427"